Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/p-dydx-guide-mhLtLSy8-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
HOST='https://api.stage.dydx.exchange'
WEB3_PROVIDER='https://goerli.infura.io/v3/5a0bd09254d94ac1af88953907f4136c'
STARK_PRIVATE_KEY=STARK_KEY_PAIRS["privateKey"]
NETWORK_ID=5

KEY=API_KEY_PAIRS["key"]
SECRET=API_KEY_PAIRS["secret"]
PASSPHRASE=API_KEY_PAIRS["passphrase"]
DEFAULT_ETHEREUM_ADDRESS=API_KEY_PAIRS["walletAddress"]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m HOST[38;5;241m=[39m[38;5;124m'[39m[38;5;124mhttps://api.stage.dydx.exchange[39m[38;5;124m'[39m
[1;32m      2[0m WEB3_PROVIDER[38;5;241m=[39m[38;5;124m'[39m[38;5;124mhttps://goerli.infura.io/v3/5a0bd09254d94ac1af88953907f4136c[39m[38;5;124m'[39m
[0;32m----> 3[0m STARK_PRIVATE_KEY[38;5;241m=[39m[43mSTARK_KEY_PAIRS[49m[[38;5;124m"[39m[38;5;124mprivateKey[39m[38;5;124m"[39m]
[1;32m      4[0m NETWORK_ID[38;5;241m=[39m[38;5;241m5[39m
[1;32m      6[0m KEY[38;5;241m=[39mAPI_KEY_PAIRS[[38;5;124m"[39m[38;5;124mkey[39m[38;5;124m"[39m]

[0;31mNameError[0m: name 'STARK_KEY_PAIRS' is not defined
NameError: name 'STARK_KEY_PAIRS' is not defined

